apiVersion: v1
kind: Service
metadata:
  name: hawkeye-sre-runbook-service
spec:
  type: NodePort
  selector:
    app: hawkeye-sre-runbook-app
  ports:
  - name: http
    port: 1313
    targetPort: 1313
    protocol: TCP

